# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/soc_lite.xdc

# IP: F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/ip/div_unsigned/div_unsigned.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_unsigned || ORIG_REF_NAME==div_unsigned} -quiet] -quiet

# IP: F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/ip/div_signed/div_signed.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_signed || ORIG_REF_NAME==div_signed} -quiet] -quiet
