# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/soft/func_lab9/obj/inst_ram.coe
read_verilog {
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_define.h
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vtools.h
}
set_property file_type "Verilog Header" [get_files F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_define.h]
set_property file_type "Verilog Header" [get_files F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vtools.h]
read_verilog -library xil_defaultlib {
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/axi_wrap/axi_wrap.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/ram_wrap/axi_wrap_ram.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/bridge2x1.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/CONFREG/confreg.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/mycpu_top.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/sram_cpu.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_ex.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_id.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_if.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_mem.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/vie_wb.v
  F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/soc_axi_lite_top.v
}
read_ip -quiet F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/ip/div_unsigned/div_unsigned.xci
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/ip/div_unsigned/div_unsigned_ooc.xdc]

read_ip -quiet F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/ip/div_signed/div_signed.xci
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/myCPU/ip/div_signed/div_signed_ooc.xdc]

read_ip -quiet F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all f:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files F:/loogson/vie_mips/axi_func_test/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/soc_lite.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_axi_lite_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
